### ISSUE TITLE
LICENSE.md for AssistDeploy

### ISSUE THREAD

**Issue by kkennedy1** [sabinio/AssistDeploy#27]
Hello!

Thank you for AssistDeploy, it does exactly what we want to do with automatic deployments of our SSIS packages. I was looking for a license for usage of this project and didn't see one. If possible, would you be able to add one? We'd really like to use it, but for my company we wouldn't be able to without knowing what license it's under.  

Thanks again!

Kevin

**Comment by RichieBzzzt** [comment]
Hello!

You are most welcome. Am very glad to hear that people are finding this useful.

I will add a licence right away. I'll add MIT to it, keep it simple.

If you do have any questions or you spot bugs/issues/improvements let me know, am always open to suggestions.

Thanks again!





---- On Fri, 29 Jun 2018 15:19:44 +0000 kkennedy1 &lt;notifications@github.com&gt; wrote ----




Hello!

Thank you for AssistDeploy, it does exactly what we want to do with automatic deployments of our SSIS packages. I was looking for a license for usage of this project and didn't see one. If possible, would you be able to add one? We'd really like to use it, but for my company we wouldn't be able to without knowing what license it's under.

Thanks again!

Kevin

**Comment by RichieBzzzt** [comment]
OK I have added MIT licence to the repo, but am currently having build issues (build agent moved resource group and hasn't been turned on in a while, so it's not code issues) therefore the licence won't be in the packages on Nuget or PowerShellGallery right now.

Hopefully this will be enough for your company right now, and once I've got the packages published I'll close the issue.

**Comment by kkennedy1** [comment]
Thank you! Once we start using it and run into anything we can try to submit a PR if you're open to that, or we can open an issue.

**Comment by kkennedy1** [comment]
It looks like my company wants to wait to review until it's merged into Master. I'll keep an eye out for when you're able to get it merged and building. Thanks again for adding the license and have a great weekend!

**Comment by RichieBzzzt** [comment]
Hello! 

No worries, I’m away for the weekend so I’ll try to get it green by Tuesday.

**Comment by RichieBzzzt** [comment]
OK sorry for the delay! I've got the build green and added license url added to nuspec file.

**Comment by kkennedy1** [comment]
No problem at all...thanks again. This will help us out a bunch with our SSIS deployments!
