### ISSUE TITLE
where is the best place to get the most recent version from?

### ISSUE THREAD

**Issue by o-o00o-o** [sabinio/AssistDeploy#34]
I'd prefer to get from powershell gallery but this seems to often be behind. currently 2.0.5942.0
nuget seems to usually be more recent 2.0.5943 but then we have to install manually from the packages folder which is a little more messy/error prone
the releasses on git hub show most recent version as 1.4.0.1 where there are versions that are 2.0 and above on the others. Are the versions > 1.4.0.1 legitimate? Do I need the latest version? How do I know?

This is a great package but it would be great if we could be clear what had changed on each version and where the most reliable place would be to get it!

Im trying to troubleshoot an issue where an old package is being deployed (not the most recent one) and when I have doubts about possible bugs in the old/new versions it just makes this more difficult, so thanks for any help on the most stable version here!

Thanks!

**Comment by RichieBzzzt** [comment]
Hello!

Master branch is indeed the latest version: the module file and nuget config version numbers get updated in the release and not in the repo. I'll concede that this can be confusing. The build and release pipelines need a bit of attention from me to make it easier to share.

I will check the discrepancy between nuget and powershellgallery: they should be on the same version.

**Comment by o-o00o-o** [comment]
great thanks. I'd like to rely on the powershellgallery one really so that would be good to get these aligned.

**Comment by RichieBzzzt** [comment]
Hi,

publishing to PowerShellGallery feed is active; it will not have the beta versions of the packages (these only appear on Nuget). The beta ones are typically used for the automation testing.

Part of the issue with version numbers when publishing powershell gallery is that it only accepts the hard coded version stored in the module manifest. Some PS Modules go and update this in the file, others leave it static and replace it in the pipeline. What I'll do is set it to 0.0.0 to keep it clear that hte version number in the manifest is not being used.
