### ISSUE TITLE
Taking Foreground during unpack

### ISSUE THREAD

**Issue by o-o00o-o** [sabinio/AssistDeploy#37]
for 30 seconds or so with our package when deploying on our local machines we get a bunch of flashes where the foreground window is being taken and released creating a flashing and it means that you can't do anything else on the screen at the time

It happens during this verbose message:

```
Creating blah\unpack
```

Any chance this could be resolved as it is a bit antisocial 😂

**Comment by RichieBzzzt** [comment]
Hello!

Thanks for the feedback. I'd like to get in touch about where the priorities are for the issues you've raised. I have an email address on my profile if you'd like to get in touch.

**Comment by RichieBzzzt** [comment]
With regards to this issue: I think this is occurring in ```Teste-ProjectParamsMatch``` - what it is doing that it is checking that the project.params file out of the ispac and checking the contents in that match the json file provided. 

https://github.com/sabinio/AssistDeploy/blob/6aa33438af99446a761445d8f860259cef5672a9/Functions/TestProjectParamsMatch.ps1#L58

~~I can try to suppress the output of the ```copyhere``` if I try to do something like this from the [docs](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/sidebar/system-shell-folder-copyhere):~~

~~``` $shell.Namespace($unpacFilepath).copyhere($item, 4) ```T~~

UPDATE: I could use [Expand-Archive](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-6).

However, and I'm loathe to say this, but I cannot replicate on my machine the flashing. I'll need to make the change then push a branch and maybe you can test for me?

**Comment by o-o00o-o** [comment]
Yeah great, happy to test.

Strange that it isn't happening for you. We are still running PS 5.1 due to .net framework dependencies for some of the ms sql 

Also I think it will only flash if you make another application foreground while the unpack is happening

``` powershell
{~\S\V\Blah} [bugfixes/blah ≡] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.771
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.771
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by RichieBzzzt** [comment]
I've removed this check as it was causing lots of problems for people as per #40
